services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: content-cleaner:local
    container_name: content-cleaner
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

